services:
    wordpress:
        image: wordpress:latest
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
        ports:
            - "8000:80"
        volumes:
            - wordpress_data:/var/www/html
        depends_on:
            - db

    db:
        image: mysql/mysql-server:8.0 # ARM-compatible version
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    wordpress_data:
    db_data:
