services:
    wordpress:
        build: ./
        environment:
            WORDPRESS_HOST_PORT: ${WORDPRESS_HOST_PORT}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
            WORDPRESS_CONFIG_WP_HOME: ${WORDPRESS_CONFIG_WP_HOME}
            WORDPRESS_CONFIG_WP_SITEURL: ${WORDPRESS_CONFIG_WP_SITEURL}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
            ADMINER_HOST_PORT: ${ADMINER_HOST_PORT}
            NEXTAPP_BASE_API_URL: ${NEXTAPP_BASE_API_URL}
            NEXTAPP_REVALIDATE_SECRET: ${NEXTAPP_REVALIDATE_SECRET}
        volumes:
            - ./:/var/www/
        ports:
            - "80:80"
        depends_on:
            - db
        networks:
            codekaizen-network:
                aliases:
                    - wordpress
                    - codekaizen-wordpress
                    - ${WORDPRESS_HOST_NAME}
            codekaizen-wordpress:

    db:
        image: mysql/mysql-server:8.0 # ARM-compatible version
        environment:
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
            MYSQL_USER: ${WORDPRESS_DB_USER}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            codekaizen-wordpress:
                aliases:
                    - db

    adminer:
        image: adminer
        ports:
            - "${ADMINER_HOST_PORT}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: db
        networks:
            codekaizen-wordpress:

networks:
    codekaizen-network:
        external: true
    codekaizen-wordpress:

volumes:
    db_data:
